name: CI

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Haal repository op
       uses: actions/checkout@v3

      -name: Installeer PHP
       uses: shivammathur/setup-php@v2
       with:
        php-version: '8.4'

      -name: Installeer dependencies
       run: composer install

      -name: Voer tests uit
       run: vendor/bin/phpunit tests